Урок 2
htmlacademy-htmlcss/1333533-device-36 pull request #2
Opened 2023-02-02 09:24 UTC by Oleg4355

В данном изменении уже прописаны и отсылки к третьему уроку с картинками . Я его тоже запушу.

2023-02-04 13:40 UTC, mkolotovich requested changes
в задании указано - выполните разметку страниц в файлах index.html и catalog.html (создать этот файл при необходимости). Вы разметили только файл index.html. Разметьте еще и файл catalog.html

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +        <label class="form-label" for="search-form-input"> Поле поиска</label>
в задании указано - Для скрытых элементов используйте класс class="visually-hidden".

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +      </div>
зачем вы дублируете эту ссылку? в макете этот текст один раз. Уберите этот элемент

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +      </div>
зачем лищние обертки для ссылок? у нас есть критерий https://up.htmlacademy.ru/htmlcss/36/criteries#HTML-06

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +        <button class="button" type="submit">Корзина
type="submit" задается для отправки данных в форме. Не вижу у вас здесь формы. Используйте type="button"

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +        <span id="Number"></span>
пропустили число 2

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +      <div>
зачем везде эти лишние обертки?

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +              <button class="button">Каталог товаров</button>
я так понимаю судя по макету, что открытие меню должно происходить при нажатии на кнопку +, которую вы не разметили, а не на "Каталог товаров"

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +              <button class="button">Доставка</button>
почему у вас здесь кнопка, а ниже такие же элементы размечены ссылками? Чем они отличаются? Верстка должна быть единообразной решили делать ссылками одинаковые элементы, делайте тогда их все ссылками

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +          <div class="сopter">
здесь и в других слайдах я считаю, что эта обертка лишняя

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +            <div class="delivery">
здесь и далее зачем эта обертка? уберите её

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +                </p>
зачем вкладывать параграф внутрь заголовка? просто сделайте их соседними элементами

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +            </div>
разметьте по аналогии с первым элементом списка

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +        </div>
зачем каждой кнопке обертка? Плюс type="submit" как я писал выше используется внутри форм. Тут форм я не вижу используйте просто type="button"

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +          <!-- фоновую картинку с браслетом и номером 02 обыграем в стиле секции с background-image  -->
вы это о чем? где вы потеряли изображение машины и кнопку i?

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +      <section>
тег section лучше использовать в блоках где есть заголовок, где заголовка нет лучше использовать div

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +        <nav class="transport">
не надо все списки со ссылками оборачитьва в тег nav. Тег nav используется для основной навигации. В вашем случае в шапке сайта.

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +        <p class="contacts-address-text">Заодно сможете проверить работоспособность покупки. </p>
это разметьте одним параграфом

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +        <p class="contacts-subtitle">Интернет -магазин Девайс </p>
это лучше разметить заголовком или тегом strong или b

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +          <a class="contacts-phone" href="tel:+78005558628">+7 800 555-86-28</a>
в макете другой телефон

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +        <p class="contacts-subtitle">Время работы</p>
это лучше разметить заголовком или тегом strong или b

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +          <label class="form-label" for="appointment-mail">Подписаться</label>
вы этот текст дублируете ниже. В макете он один раз. Можете скрывать его с помощью класса visually-hidden

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +          <a class="contacts-phone" href="tel:+78005558628">+7 800 555-86-28</a>
здесь в макете телефона нет. Телефон только с правой стороны в макете в подвале

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +      </li>
теги li могут лежать только внутри списка, например ul

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +        <a class="secondmenu-link" href="Contacts.html">Контакты</a>
почему хздесь кнопка, а дальше ссылки? чем оличаются эти элементы? верстка подобных элементов должна быть идентична

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +      <section class="footer-social"><a class="contacts-phone" href="tel:+78005558628">+7 800 555-86-28</a>
я уже писал выше по поводу тега section, что его лучше использовать в блоках где есть заголовки. По поводу телефона, такого номера в макете нет

2023-02-04 13:40 UTC, mkolotovich commented on index.html
> +        <p class="about-text"> <a class="htmlacademy-link" href="https://htmlacademy.ru/">.html academy</a></p>
зачем оборачивать ссылку в параграф? тут наоборот текст .html academy необходимо вставить изображением, а само изображение обернуть в ссылку

2023-02-07 12:17 UTC, Oleg4355 commented on index.html
> +        <span id="Number"></span>
Разметка всех страниц new

2023-02-08 17:32 UTC, Oleg4355 commented on index.html
> +        <label class="form-label" for="search-form-input"> Поле поиска</label>
Использовано строке 13.

2023-02-08 17:48 UTC, Oleg4355 commented on index.html
> +      </div>
Убрал.

2023-02-08 17:51 UTC, Oleg4355 commented on index.html
> +        <button class="button" type="submit">Корзина
Внес.

2023-02-08 17:51 UTC, Oleg4355 commented on index.html
> +        <span id="Number"></span>
Исправил

2023-02-08 17:53 UTC, Oleg4355 commented on index.html
> +      <div>
Исправил

2023-02-08 18:15 UTC, Oleg4355 commented on index.html
> +              <button class="button">Каталог товаров</button>
Окрытие меню в Фигме происходит и при нажатии на Катало товаров ,и при нажатии на кнопку плюс. Как их сгруппировать -я не знаю. Можно использовать <fieldset>???

2023-02-08 18:21 UTC, Oleg4355 commented on index.html
> +              <button class="button">Доставка</button>
Согласен. Решил сделать все кнопками.ибо действие происходит на странице той же.

2023-02-08 18:25 UTC, Oleg4355 commented on index.html
> +            <div class="delivery">
Если уберу -все рассыпется. Спорно. Надо обсуждать.

2023-02-08 18:39 UTC, Oleg4355 commented on index.html
> +              <button class="button">Доставка</button>
И снова все исправил. Все сделал ссылками.Так как в Фигме при включении режима прототипирования при клике перебрасывает в другую часть страницы.

2023-02-09 12:55 UTC, Oleg4355 commented on index.html
> +                </p>
Сделал

2023-02-09 13:00 UTC, Oleg4355 commented on index.html
> +            </div>
Исправил

2023-02-09 13:11 UTC, Oleg4355 commented on index.html
> +      <section>
Исправил

2023-02-09 13:17 UTC, Oleg4355 commented on index.html
> +        <p class="contacts-address-text">Заодно сможете проверить работоспособность покупки. </p>
Есть

2023-02-09 13:18 UTC, Oleg4355 commented on index.html
> +          <a class="contacts-phone" href="tel:+78005558628">+7 800 555-86-28</a>
Исправил

2023-02-13 15:15 UTC, uzinok reviewed
https://skr.sh/sINOcDNwMdb это разве фоновая картинка?
https://skr.sh/sINAQ95Gg4Z если это таблица, то у неё есть "заголовки" как и у колонок, так и у самой таблицы
https://skr.sh/sINPc1Kfbbt проверь на валидность разметку https://validator.w3.org/nu/#textarea
https://skr.sh/sINEuwZHwkV мы же вроде обсуждали этот момент: тут должен быть заголовок
https://skr.sh/sINix8EZk8p а почему слайдер не в майн?
https://skr.sh/sINdoFGvP6Z даже визуально логотип не может быть в теге `address`
в футере нарушен порядок элементов, можно позже поправить
в каталоге не все элементы добавлены (кроме поля со стоимостью)
https://skr.sh/sINXQRJ7Z2b даже визуально эти кнопки вне списка
нарушен порядок элементов

2023-02-21 11:48 UTC, uzinok reviewed
https://skr.sh/sIV1JyqxA9U где фото товара?
для чего список из одного элемента? что бы жизнь пользователя мёдом не казалась?
остальное пойдёт, позже сам увидишь что не так и поправишь))

2023-02-21 11:48 UTC, merged